### ISSUE TITLE
Trigger merge + builds on Custom PR approval

### ISSUE THREAD

**Issue by missaugustina** [RConsortium/blog-sandbox#5]
Create editor role. Merge to master when a PR receives approvals from roles.

**Comment by missaugustina** [comment]
Ideally we would have 2 but for v1, 1 is sufficient.

**Comment by owenjonesuob** [comment]
Could we have a "team" of editors? https://help.github.com/articles/creating-a-team/

I _think_ we could then allow this team to review PRs on the repo, and set `master` as a protected branch:

![image](https://user-images.githubusercontent.com/21007837/38256274-c92a0f18-3755-11e8-9b89-60f2bcbd5ab5.png)

**Comment by missaugustina** [comment]
This is exactly the kind of thing I was thinking of. Usually with group-based systems, there's some kind of roles-based permissions and people are added to the roles.

**Comment by missaugustina** [comment]
Notes from email I sent to Owen
========================

For the Travis workflow, I need to find an example of what I'm thinking of (although you might have some clue) and update the ticket. This what I could find quickly - https://github.com/BonnyCI/bonnyci.org/pull/65 Towards the bottom there's an event "Jesusaurus approved these changes". This one is in a state of "review required" https://github.com/BonnyCI/hoist/pull/510 Something to note, this was a custom CI thing I was working on with some others that did have some TravisCI pieces. TravisCI won't look or act exactly like that, but the point was to show you what is in my head!!
 
Requirements for submission -- user has to run the blogdown locally to convert the R markdown to HTML. TravisCI will run Hugo to generate the static site.
 
1) new PR submitted -> TravisCI runs checks/builds Hugo -> PR status is "needs review" (some kind of status indicating someone needs to review it, doesn't have to be this exactly, not sure what Travis supports)
2) user with +1 ability approves PR -> TravisCI runs checks/builds Hugo, merges, deploys
 
I'll update the issue with more details when I have time to review the Travis docs, also feel free to add any links/notes/ideas you find or come up with.

**Comment by missaugustina** [comment]
I've implemented this on this repo.

1. Create a team of Editors
1. Branch settings - set master to protected, require the appropriate number of reviews before a PR can be merged
1. Set teams that can push to the Editors team

A future version of this could create different teams of editors. For now we'll just stick with one and indicate how many people need to approve a new post.
